export interface Country {
  code: string;
  name: string;
  currency: string;
  currencySymbol: string;
  region: string;
}

export interface Currency {
  code: string;
  symbol: string;
  name: string;
  conversionRate: number;
}

export interface GlobalLanguage {
  code: string;
  name: string;
  nativeName: string;
  rtl: boolean;
  region: string;
}

export const ALL_COUNTRIES: Country[] = [
  { code: 'US', name: 'United States', currency: 'USD', currencySymbol: '$', region: 'North America' },
  { code: 'IN', name: 'India', currency: 'INR', currencySymbol: '₹', region: 'Asia' },
  { code: 'GB', name: 'United Kingdom', currency: 'GBP', currencySymbol: '£', region: 'Europe' },
  { code: 'CA', name: 'Canada', currency: 'CAD', currencySymbol: 'C$', region: 'North America' },
  { code: 'AU', name: 'Australia', currency: 'AUD', currencySymbol: 'A$', region: 'Oceania' },
  { code: 'DE', name: 'Germany', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'FR', name: 'France', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'IT', name: 'Italy', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'ES', name: 'Spain', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'NL', name: 'Netherlands', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'BE', name: 'Belgium', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'AT', name: 'Austria', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'IE', name: 'Ireland', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'PT', name: 'Portugal', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'GR', name: 'Greece', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'FI', name: 'Finland', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'CH', name: 'Switzerland', currency: 'CHF', currencySymbol: 'CHF', region: 'Europe' },
  { code: 'SE', name: 'Sweden', currency: 'SEK', currencySymbol: 'kr', region: 'Europe' },
  { code: 'NO', name: 'Norway', currency: 'NOK', currencySymbol: 'kr', region: 'Europe' },
  { code: 'DK', name: 'Denmark', currency: 'DKK', currencySymbol: 'kr', region: 'Europe' },
  { code: 'PL', name: 'Poland', currency: 'PLN', currencySymbol: 'zł', region: 'Europe' },
  { code: 'CZ', name: 'Czech Republic', currency: 'CZK', currencySymbol: 'Kč', region: 'Europe' },
  { code: 'HU', name: 'Hungary', currency: 'HUF', currencySymbol: 'Ft', region: 'Europe' },
  { code: 'RO', name: 'Romania', currency: 'RON', currencySymbol: 'lei', region: 'Europe' },
  { code: 'BG', name: 'Bulgaria', currency: 'BGN', currencySymbol: 'лв', region: 'Europe' },
  { code: 'HR', name: 'Croatia', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'RS', name: 'Serbia', currency: 'RSD', currencySymbol: 'дин', region: 'Europe' },
  { code: 'UA', name: 'Ukraine', currency: 'UAH', currencySymbol: '₴', region: 'Europe' },
  { code: 'RU', name: 'Russia', currency: 'RUB', currencySymbol: '₽', region: 'Europe/Asia' },
  { code: 'TR', name: 'Turkey', currency: 'TRY', currencySymbol: '₺', region: 'Europe/Asia' },
  { code: 'JP', name: 'Japan', currency: 'JPY', currencySymbol: '¥', region: 'Asia' },
  { code: 'CN', name: 'China', currency: 'CNY', currencySymbol: '¥', region: 'Asia' },
  { code: 'KR', name: 'South Korea', currency: 'KRW', currencySymbol: '₩', region: 'Asia' },
  { code: 'SG', name: 'Singapore', currency: 'SGD', currencySymbol: 'S$', region: 'Asia' },
  { code: 'HK', name: 'Hong Kong', currency: 'HKD', currencySymbol: 'HK$', region: 'Asia' },
  { code: 'TW', name: 'Taiwan', currency: 'TWD', currencySymbol: 'NT$', region: 'Asia' },
  { code: 'MY', name: 'Malaysia', currency: 'MYR', currencySymbol: 'RM', region: 'Asia' },
  { code: 'TH', name: 'Thailand', currency: 'THB', currencySymbol: '฿', region: 'Asia' },
  { code: 'ID', name: 'Indonesia', currency: 'IDR', currencySymbol: 'Rp', region: 'Asia' },
  { code: 'PH', name: 'Philippines', currency: 'PHP', currencySymbol: '₱', region: 'Asia' },
  { code: 'VN', name: 'Vietnam', currency: 'VND', currencySymbol: '₫', region: 'Asia' },
  { code: 'BD', name: 'Bangladesh', currency: 'BDT', currencySymbol: '৳', region: 'Asia' },
  { code: 'PK', name: 'Pakistan', currency: 'PKR', currencySymbol: '₨', region: 'Asia' },
  { code: 'LK', name: 'Sri Lanka', currency: 'LKR', currencySymbol: 'Rs', region: 'Asia' },
  { code: 'NP', name: 'Nepal', currency: 'NPR', currencySymbol: 'Rs', region: 'Asia' },
  { code: 'MM', name: 'Myanmar', currency: 'MMK', currencySymbol: 'K', region: 'Asia' },
  { code: 'KH', name: 'Cambodia', currency: 'KHR', currencySymbol: '៛', region: 'Asia' },
  { code: 'LA', name: 'Laos', currency: 'LAK', currencySymbol: '₭', region: 'Asia' },
  { code: 'AE', name: 'United Arab Emirates', currency: 'AED', currencySymbol: 'د.إ', region: 'Middle East' },
  { code: 'SA', name: 'Saudi Arabia', currency: 'SAR', currencySymbol: 'ر.س', region: 'Middle East' },
  { code: 'QA', name: 'Qatar', currency: 'QAR', currencySymbol: 'ر.ق', region: 'Middle East' },
  { code: 'KW', name: 'Kuwait', currency: 'KWD', currencySymbol: 'د.ك', region: 'Middle East' },
  { code: 'BH', name: 'Bahrain', currency: 'BHD', currencySymbol: 'د.ب', region: 'Middle East' },
  { code: 'OM', name: 'Oman', currency: 'OMR', currencySymbol: 'ر.ع', region: 'Middle East' },
  { code: 'IL', name: 'Israel', currency: 'ILS', currencySymbol: '₪', region: 'Middle East' },
  { code: 'JO', name: 'Jordan', currency: 'JOD', currencySymbol: 'د.ا', region: 'Middle East' },
  { code: 'LB', name: 'Lebanon', currency: 'LBP', currencySymbol: 'ل.ل', region: 'Middle East' },
  { code: 'IQ', name: 'Iraq', currency: 'IQD', currencySymbol: 'ع.د', region: 'Middle East' },
  { code: 'IR', name: 'Iran', currency: 'IRR', currencySymbol: '﷼', region: 'Middle East' },
  { code: 'EG', name: 'Egypt', currency: 'EGP', currencySymbol: 'E£', region: 'Africa' },
  { code: 'ZA', name: 'South Africa', currency: 'ZAR', currencySymbol: 'R', region: 'Africa' },
  { code: 'NG', name: 'Nigeria', currency: 'NGN', currencySymbol: '₦', region: 'Africa' },
  { code: 'KE', name: 'Kenya', currency: 'KES', currencySymbol: 'KSh', region: 'Africa' },
  { code: 'GH', name: 'Ghana', currency: 'GHS', currencySymbol: '₵', region: 'Africa' },
  { code: 'TZ', name: 'Tanzania', currency: 'TZS', currencySymbol: 'TSh', region: 'Africa' },
  { code: 'UG', name: 'Uganda', currency: 'UGX', currencySymbol: 'USh', region: 'Africa' },
  { code: 'ET', name: 'Ethiopia', currency: 'ETB', currencySymbol: 'Br', region: 'Africa' },
  { code: 'MA', name: 'Morocco', currency: 'MAD', currencySymbol: 'د.م.', region: 'Africa' },
  { code: 'DZ', name: 'Algeria', currency: 'DZD', currencySymbol: 'د.ج', region: 'Africa' },
  { code: 'TN', name: 'Tunisia', currency: 'TND', currencySymbol: 'د.ت', region: 'Africa' },
  { code: 'BR', name: 'Brazil', currency: 'BRL', currencySymbol: 'R$', region: 'South America' },
  { code: 'MX', name: 'Mexico', currency: 'MXN', currencySymbol: '$', region: 'North America' },
  { code: 'AR', name: 'Argentina', currency: 'ARS', currencySymbol: '$', region: 'South America' },
  { code: 'CL', name: 'Chile', currency: 'CLP', currencySymbol: '$', region: 'South America' },
  { code: 'CO', name: 'Colombia', currency: 'COP', currencySymbol: '$', region: 'South America' },
  { code: 'PE', name: 'Peru', currency: 'PEN', currencySymbol: 'S/', region: 'South America' },
  { code: 'VE', name: 'Venezuela', currency: 'VES', currencySymbol: 'Bs.', region: 'South America' },
  { code: 'EC', name: 'Ecuador', currency: 'USD', currencySymbol: '$', region: 'South America' },
  { code: 'UY', name: 'Uruguay', currency: 'UYU', currencySymbol: '$U', region: 'South America' },
  { code: 'PY', name: 'Paraguay', currency: 'PYG', currencySymbol: '₲', region: 'South America' },
  { code: 'BO', name: 'Bolivia', currency: 'BOB', currencySymbol: 'Bs.', region: 'South America' },
  { code: 'CR', name: 'Costa Rica', currency: 'CRC', currencySymbol: '₡', region: 'Central America' },
  { code: 'PA', name: 'Panama', currency: 'PAB', currencySymbol: 'B/.', region: 'Central America' },
  { code: 'GT', name: 'Guatemala', currency: 'GTQ', currencySymbol: 'Q', region: 'Central America' },
  { code: 'NZ', name: 'New Zealand', currency: 'NZD', currencySymbol: 'NZ$', region: 'Oceania' },
  { code: 'FJ', name: 'Fiji', currency: 'FJD', currencySymbol: 'FJ$', region: 'Oceania' },
  { code: 'IS', name: 'Iceland', currency: 'ISK', currencySymbol: 'kr', region: 'Europe' },
  { code: 'LT', name: 'Lithuania', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'LV', name: 'Latvia', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'EE', name: 'Estonia', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'SI', name: 'Slovenia', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'SK', name: 'Slovakia', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'MT', name: 'Malta', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'CY', name: 'Cyprus', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'LU', name: 'Luxembourg', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'BY', name: 'Belarus', currency: 'BYN', currencySymbol: 'Br', region: 'Europe' },
  { code: 'MD', name: 'Moldova', currency: 'MDL', currencySymbol: 'L', region: 'Europe' },
  { code: 'AL', name: 'Albania', currency: 'ALL', currencySymbol: 'L', region: 'Europe' },
  { code: 'MK', name: 'North Macedonia', currency: 'MKD', currencySymbol: 'ден', region: 'Europe' },
  { code: 'BA', name: 'Bosnia and Herzegovina', currency: 'BAM', currencySymbol: 'KM', region: 'Europe' },
  { code: 'ME', name: 'Montenegro', currency: 'EUR', currencySymbol: '€', region: 'Europe' },
  { code: 'KZ', name: 'Kazakhstan', currency: 'KZT', currencySymbol: '₸', region: 'Asia' },
  { code: 'UZ', name: 'Uzbekistan', currency: 'UZS', currencySymbol: 'so\'m', region: 'Asia' },
  { code: 'GE', name: 'Georgia', currency: 'GEL', currencySymbol: '₾', region: 'Asia' },
  { code: 'AM', name: 'Armenia', currency: 'AMD', currencySymbol: '֏', region: 'Asia' },
  { code: 'AZ', name: 'Azerbaijan', currency: 'AZN', currencySymbol: '₼', region: 'Asia' },
  { code: 'MN', name: 'Mongolia', currency: 'MNT', currencySymbol: '₮', region: 'Asia' },
  { code: 'AF', name: 'Afghanistan', currency: 'AFN', currencySymbol: '؋', region: 'Asia' },
  { code: 'BN', name: 'Brunei', currency: 'BND', currencySymbol: 'B$', region: 'Asia' },
  { code: 'MV', name: 'Maldives', currency: 'MVR', currencySymbol: 'Rf', region: 'Asia' },
  { code: 'BT', name: 'Bhutan', currency: 'BTN', currencySymbol: 'Nu.', region: 'Asia' },
  { code: 'SY', name: 'Syria', currency: 'SYP', currencySymbol: '£S', region: 'Middle East' },
  { code: 'YE', name: 'Yemen', currency: 'YER', currencySymbol: '﷼', region: 'Middle East' },
  { code: 'PS', name: 'Palestine', currency: 'ILS', currencySymbol: '₪', region: 'Middle East' },
  { code: 'LY', name: 'Libya', currency: 'LYD', currencySymbol: 'ل.د', region: 'Africa' },
  { code: 'SD', name: 'Sudan', currency: 'SDG', currencySymbol: 'ج.س.', region: 'Africa' },
  { code: 'SO', name: 'Somalia', currency: 'SOS', currencySymbol: 'Sh', region: 'Africa' },
  { code: 'DJ', name: 'Djibouti', currency: 'DJF', currencySymbol: 'Fdj', region: 'Africa' },
  { code: 'ER', name: 'Eritrea', currency: 'ERN', currencySymbol: 'Nfk', region: 'Africa' },
  { code: 'ZW', name: 'Zimbabwe', currency: 'ZWL', currencySymbol: 'Z$', region: 'Africa' },
  { code: 'ZM', name: 'Zambia', currency: 'ZMW', currencySymbol: 'ZK', region: 'Africa' },
  { code: 'MW', name: 'Malawi', currency: 'MWK', currencySymbol: 'MK', region: 'Africa' },
  { code: 'MZ', name: 'Mozambique', currency: 'MZN', currencySymbol: 'MT', region: 'Africa' },
  { code: 'BW', name: 'Botswana', currency: 'BWP', currencySymbol: 'P', region: 'Africa' },
  { code: 'NA', name: 'Namibia', currency: 'NAD', currencySymbol: 'N$', region: 'Africa' },
  { code: 'AO', name: 'Angola', currency: 'AOA', currencySymbol: 'Kz', region: 'Africa' },
  { code: 'CD', name: 'DR Congo', currency: 'CDF', currencySymbol: 'FC', region: 'Africa' },
  { code: 'CG', name: 'Congo', currency: 'XAF', currencySymbol: 'FCFA', region: 'Africa' },
  { code: 'CM', name: 'Cameroon', currency: 'XAF', currencySymbol: 'FCFA', region: 'Africa' },
  { code: 'GA', name: 'Gabon', currency: 'XAF', currencySymbol: 'FCFA', region: 'Africa' },
  { code: 'TD', name: 'Chad', currency: 'XAF', currencySymbol: 'FCFA', region: 'Africa' },
  { code: 'CF', name: 'Central African Republic', currency: 'XAF', currencySymbol: 'FCFA', region: 'Africa' },
  { code: 'GQ', name: 'Equatorial Guinea', currency: 'XAF', currencySymbol: 'FCFA', region: 'Africa' },
  { code: 'CI', name: 'Ivory Coast', currency: 'XOF', currencySymbol: 'CFA', region: 'Africa' },
  { code: 'SN', name: 'Senegal', currency: 'XOF', currencySymbol: 'CFA', region: 'Africa' },
  { code: 'ML', name: 'Mali', currency: 'XOF', currencySymbol: 'CFA', region: 'Africa' },
  { code: 'BF', name: 'Burkina Faso', currency: 'XOF', currencySymbol: 'CFA', region: 'Africa' },
  { code: 'NE', name: 'Niger', currency: 'XOF', currencySymbol: 'CFA', region: 'Africa' },
  { code: 'TG', name: 'Togo', currency: 'XOF', currencySymbol: 'CFA', region: 'Africa' },
  { code: 'BJ', name: 'Benin', currency: 'XOF', currencySymbol: 'CFA', region: 'Africa' },
  { code: 'GN', name: 'Guinea', currency: 'GNF', currencySymbol: 'FG', region: 'Africa' },
  { code: 'SL', name: 'Sierra Leone', currency: 'SLL', currencySymbol: 'Le', region: 'Africa' },
  { code: 'LR', name: 'Liberia', currency: 'LRD', currencySymbol: 'L$', region: 'Africa' },
  { code: 'GM', name: 'Gambia', currency: 'GMD', currencySymbol: 'D', region: 'Africa' },
  { code: 'MR', name: 'Mauritania', currency: 'MRU', currencySymbol: 'UM', region: 'Africa' },
  { code: 'RW', name: 'Rwanda', currency: 'RWF', currencySymbol: 'FRw', region: 'Africa' },
  { code: 'BI', name: 'Burundi', currency: 'BIF', currencySymbol: 'FBu', region: 'Africa' },
  { code: 'MU', name: 'Mauritius', currency: 'MUR', currencySymbol: '₨', region: 'Africa' },
  { code: 'SC', name: 'Seychelles', currency: 'SCR', currencySymbol: '₨', region: 'Africa' },
  { code: 'MG', name: 'Madagascar', currency: 'MGA', currencySymbol: 'Ar', region: 'Africa' },
  { code: 'KM', name: 'Comoros', currency: 'KMF', currencySymbol: 'CF', region: 'Africa' },
  { code: 'CV', name: 'Cape Verde', currency: 'CVE', currencySymbol: '$', region: 'Africa' },
  { code: 'ST', name: 'São Tomé and Príncipe', currency: 'STN', currencySymbol: 'Db', region: 'Africa' },
  { code: 'SZ', name: 'Eswatini', currency: 'SZL', currencySymbol: 'E', region: 'Africa' },
  { code: 'LS', name: 'Lesotho', currency: 'LSL', currencySymbol: 'L', region: 'Africa' },
  { code: 'HN', name: 'Honduras', currency: 'HNL', currencySymbol: 'L', region: 'Central America' },
  { code: 'NI', name: 'Nicaragua', currency: 'NIO', currencySymbol: 'C$', region: 'Central America' },
  { code: 'SV', name: 'El Salvador', currency: 'USD', currencySymbol: '$', region: 'Central America' },
  { code: 'BZ', name: 'Belize', currency: 'BZD', currencySymbol: 'BZ$', region: 'Central America' },
  { code: 'JM', name: 'Jamaica', currency: 'JMD', currencySymbol: 'J$', region: 'Caribbean' },
  { code: 'TT', name: 'Trinidad and Tobago', currency: 'TTD', currencySymbol: 'TT$', region: 'Caribbean' },
  { code: 'BS', name: 'Bahamas', currency: 'BSD', currencySymbol: 'B$', region: 'Caribbean' },
  { code: 'BB', name: 'Barbados', currency: 'BBD', currencySymbol: 'Bds$', region: 'Caribbean' },
  { code: 'DO', name: 'Dominican Republic', currency: 'DOP', currencySymbol: 'RD$', region: 'Caribbean' },
  { code: 'HT', name: 'Haiti', currency: 'HTG', currencySymbol: 'G', region: 'Caribbean' },
  { code: 'CU', name: 'Cuba', currency: 'CUP', currencySymbol: '₱', region: 'Caribbean' },
  { code: 'GY', name: 'Guyana', currency: 'GYD', currencySymbol: 'G$', region: 'South America' },
  { code: 'SR', name: 'Suriname', currency: 'SRD', currencySymbol: 'Sr$', region: 'South America' },
  { code: 'PG', name: 'Papua New Guinea', currency: 'PGK', currencySymbol: 'K', region: 'Oceania' },
  { code: 'SB', name: 'Solomon Islands', currency: 'SBD', currencySymbol: 'SI$', region: 'Oceania' },
  { code: 'VU', name: 'Vanuatu', currency: 'VUV', currencySymbol: 'VT', region: 'Oceania' },
  { code: 'WS', name: 'Samoa', currency: 'WST', currencySymbol: 'WS$', region: 'Oceania' },
  { code: 'TO', name: 'Tonga', currency: 'TOP', currencySymbol: 'T$', region: 'Oceania' },
  { code: 'KI', name: 'Kiribati', currency: 'AUD', currencySymbol: 'A$', region: 'Oceania' },
  { code: 'TV', name: 'Tuvalu', currency: 'AUD', currencySymbol: 'A$', region: 'Oceania' },
  { code: 'NR', name: 'Nauru', currency: 'AUD', currencySymbol: 'A$', region: 'Oceania' },
  { code: 'PW', name: 'Palau', currency: 'USD', currencySymbol: '$', region: 'Oceania' },
  { code: 'FM', name: 'Micronesia', currency: 'USD', currencySymbol: '$', region: 'Oceania' },
  { code: 'MH', name: 'Marshall Islands', currency: 'USD', currencySymbol: '$', region: 'Oceania' },
];

export const ALL_CURRENCIES: Currency[] = [
  { code: 'USD', symbol: '$', name: 'US Dollar', conversionRate: 1 },
  { code: 'EUR', symbol: '€', name: 'Euro', conversionRate: 0.92 },
  { code: 'GBP', symbol: '£', name: 'British Pound', conversionRate: 0.79 },
  { code: 'INR', symbol: '₹', name: 'Indian Rupee', conversionRate: 83.12 },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen', conversionRate: 149.50 },
  { code: 'CNY', symbol: '¥', name: 'Chinese Yuan', conversionRate: 7.24 },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', conversionRate: 1.52 },
  { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar', conversionRate: 1.36 },
  { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc', conversionRate: 0.88 },
  { code: 'SEK', symbol: 'kr', name: 'Swedish Krona', conversionRate: 10.58 },
  { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', conversionRate: 1.65 },
  { code: 'KRW', symbol: '₩', name: 'South Korean Won', conversionRate: 1325.00 },
  { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar', conversionRate: 1.34 },
  { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar', conversionRate: 7.82 },
  { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone', conversionRate: 10.75 },
  { code: 'MXN', symbol: '$', name: 'Mexican Peso', conversionRate: 17.15 },
  { code: 'BRL', symbol: 'R$', name: 'Brazilian Real', conversionRate: 4.98 },
  { code: 'ZAR', symbol: 'R', name: 'South African Rand', conversionRate: 18.35 },
  { code: 'RUB', symbol: '₽', name: 'Russian Ruble', conversionRate: 92.50 },
  { code: 'TRY', symbol: '₺', name: 'Turkish Lira', conversionRate: 32.15 },
  { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham', conversionRate: 3.67 },
  { code: 'SAR', symbol: 'ر.س', name: 'Saudi Riyal', conversionRate: 3.75 },
  { code: 'THB', symbol: '฿', name: 'Thai Baht', conversionRate: 35.20 },
  { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah', conversionRate: 15680.00 },
  { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit', conversionRate: 4.47 },
  { code: 'PHP', symbol: '₱', name: 'Philippine Peso', conversionRate: 56.35 },
  { code: 'VND', symbol: '₫', name: 'Vietnamese Dong', conversionRate: 24500.00 },
  { code: 'PLN', symbol: 'zł', name: 'Polish Złoty', conversionRate: 4.02 },
  { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna', conversionRate: 22.85 },
  { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint', conversionRate: 355.00 },
  { code: 'DKK', symbol: 'kr', name: 'Danish Krone', conversionRate: 6.87 },
  { code: 'ILS', symbol: '₪', name: 'Israeli Shekel', conversionRate: 3.68 },
  { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound', conversionRate: 49.00 },
  { code: 'NGN', symbol: '₦', name: 'Nigerian Naira', conversionRate: 1565.00 },
  { code: 'ARS', symbol: '$', name: 'Argentine Peso', conversionRate: 850.00 },
  { code: 'CLP', symbol: '$', name: 'Chilean Peso', conversionRate: 975.00 },
  { code: 'COP', symbol: '$', name: 'Colombian Peso', conversionRate: 4025.00 },
  { code: 'PEN', symbol: 'S/', name: 'Peruvian Sol', conversionRate: 3.72 },
  { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee', conversionRate: 278.50 },
  { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka', conversionRate: 109.50 },
  { code: 'TWD', symbol: 'NT$', name: 'Taiwan Dollar', conversionRate: 31.50 },
  { code: 'RON', symbol: 'lei', name: 'Romanian Leu', conversionRate: 4.56 },
  { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev', conversionRate: 1.80 },
  { code: 'RSD', symbol: 'дин', name: 'Serbian Dinar', conversionRate: 107.50 },
  { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia', conversionRate: 36.85 },
  { code: 'QAR', symbol: 'ر.ق', name: 'Qatari Riyal', conversionRate: 3.64 },
  { code: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar', conversionRate: 0.31 },
  { code: 'BHD', symbol: 'د.ب', name: 'Bahraini Dinar', conversionRate: 0.38 },
  { code: 'OMR', symbol: 'ر.ع', name: 'Omani Rial', conversionRate: 0.38 },
  { code: 'JOD', symbol: 'د.ا', name: 'Jordanian Dinar', conversionRate: 0.71 },
  { code: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound', conversionRate: 89500.00 },
  { code: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar', conversionRate: 1310.00 },
  { code: 'IRR', symbol: '﷼', name: 'Iranian Rial', conversionRate: 42000.00 },
  { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling', conversionRate: 129.50 },
  { code: 'GHS', symbol: '₵', name: 'Ghanaian Cedi', conversionRate: 15.80 },
  { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling', conversionRate: 2515.00 },
  { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling', conversionRate: 3685.00 },
  { code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr', conversionRate: 112.50 },
  { code: 'MAD', symbol: 'د.م.', name: 'Moroccan Dirham', conversionRate: 10.15 },
  { code: 'DZD', symbol: 'د.ج', name: 'Algerian Dinar', conversionRate: 134.50 },
  { code: 'TND', symbol: 'د.ت', name: 'Tunisian Dinar', conversionRate: 3.12 },
  { code: 'VES', symbol: 'Bs.', name: 'Venezuelan Bolívar', conversionRate: 36.50 },
  { code: 'UYU', symbol: '$U', name: 'Uruguayan Peso', conversionRate: 39.25 },
  { code: 'PYG', symbol: '₲', name: 'Paraguayan Guaraní', conversionRate: 7285.00 },
  { code: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano', conversionRate: 6.91 },
  { code: 'CRC', symbol: '₡', name: 'Costa Rican Colón', conversionRate: 511.00 },
  { code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa', conversionRate: 1 },
  { code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal', conversionRate: 7.78 },
  { code: 'FJD', symbol: 'FJ$', name: 'Fijian Dollar', conversionRate: 2.24 },
  { code: 'ISK', symbol: 'kr', name: 'Icelandic Króna', conversionRate: 137.50 },
  { code: 'BYN', symbol: 'Br', name: 'Belarusian Ruble', conversionRate: 3.18 },
  { code: 'MDL', symbol: 'L', name: 'Moldovan Leu', conversionRate: 17.85 },
  { code: 'ALL', symbol: 'L', name: 'Albanian Lek', conversionRate: 93.50 },
  { code: 'MKD', symbol: 'ден', name: 'Macedonian Denar', conversionRate: 56.75 },
  { code: 'BAM', symbol: 'KM', name: 'Bosnia-Herzegovina Mark', conversionRate: 1.80 },
  { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge', conversionRate: 452.00 },
  { code: 'UZS', symbol: 'so\'m', name: 'Uzbekistani Som', conversionRate: 12650.00 },
  { code: 'GEL', symbol: '₾', name: 'Georgian Lari', conversionRate: 2.68 },
  { code: 'AMD', symbol: '֏', name: 'Armenian Dram', conversionRate: 387.50 },
  { code: 'AZN', symbol: '₼', name: 'Azerbaijani Manat', conversionRate: 1.70 },
  { code: 'MNT', symbol: '₮', name: 'Mongolian Tögrög', conversionRate: 3450.00 },
  { code: 'AFN', symbol: '؋', name: 'Afghan Afghani', conversionRate: 70.50 },
  { code: 'BND', symbol: 'B$', name: 'Brunei Dollar', conversionRate: 1.34 },
  { code: 'MVR', symbol: 'Rf', name: 'Maldivian Rufiyaa', conversionRate: 15.40 },
  { code: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum', conversionRate: 83.20 },
  { code: 'SYP', symbol: '£S', name: 'Syrian Pound', conversionRate: 13000.00 },
  { code: 'YER', symbol: '﷼', name: 'Yemeni Rial', conversionRate: 250.00 },
  { code: 'LYD', symbol: 'ل.د', name: 'Libyan Dinar', conversionRate: 4.82 },
  { code: 'SDG', symbol: 'ج.س.', name: 'Sudanese Pound', conversionRate: 601.00 },
  { code: 'SOS', symbol: 'Sh', name: 'Somali Shilling', conversionRate: 571.00 },
  { code: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc', conversionRate: 177.50 },
  { code: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa', conversionRate: 15.00 },
  { code: 'ZWL', symbol: 'Z$', name: 'Zimbabwean Dollar', conversionRate: 322.00 },
  { code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha', conversionRate: 26.85 },
  { code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha', conversionRate: 1730.00 },
  { code: 'MZN', symbol: 'MT', name: 'Mozambican Metical', conversionRate: 63.85 },
  { code: 'BWP', symbol: 'P', name: 'Botswana Pula', conversionRate: 13.45 },
  { code: 'NAD', symbol: 'N$', name: 'Namibian Dollar', conversionRate: 18.35 },
  { code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza', conversionRate: 925.00 },
  { code: 'CDF', symbol: 'FC', name: 'Congolese Franc', conversionRate: 2825.00 },
  { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', conversionRate: 603.00 },
  { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', conversionRate: 603.00 },
  { code: 'GNF', symbol: 'FG', name: 'Guinean Franc', conversionRate: 8600.00 },
  { code: 'SLL', symbol: 'Le', name: 'Sierra Leonean Leone', conversionRate: 22500.00 },
  { code: 'LRD', symbol: 'L$', name: 'Liberian Dollar', conversionRate: 188.50 },
  { code: 'GMD', symbol: 'D', name: 'Gambian Dalasi', conversionRate: 67.50 },
  { code: 'MRU', symbol: 'UM', name: 'Mauritanian Ouguiya', conversionRate: 39.75 },
  { code: 'RWF', symbol: 'FRw', name: 'Rwandan Franc', conversionRate: 1365.00 },
  { code: 'BIF', symbol: 'FBu', name: 'Burundian Franc', conversionRate: 2870.00 },
  { code: 'MUR', symbol: '₨', name: 'Mauritian Rupee', conversionRate: 45.85 },
  { code: 'SCR', symbol: '₨', name: 'Seychellois Rupee', conversionRate: 13.65 },
  { code: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary', conversionRate: 4525.00 },
  { code: 'KMF', symbol: 'CF', name: 'Comorian Franc', conversionRate: 452.00 },
  { code: 'CVE', symbol: '$', name: 'Cape Verdean Escudo', conversionRate: 101.50 },
  { code: 'STN', symbol: 'Db', name: 'São Tomé & Príncipe Dobra', conversionRate: 22.50 },
  { code: 'SZL', symbol: 'E', name: 'Swazi Lilangeni', conversionRate: 18.35 },
  { code: 'LSL', symbol: 'L', name: 'Lesotho Loti', conversionRate: 18.35 },
  { code: 'HNL', symbol: 'L', name: 'Honduran Lempira', conversionRate: 24.75 },
  { code: 'NIO', symbol: 'C$', name: 'Nicaraguan Córdoba', conversionRate: 36.85 },
  { code: 'BZD', symbol: 'BZ$', name: 'Belize Dollar', conversionRate: 2.02 },
  { code: 'JMD', symbol: 'J$', name: 'Jamaican Dollar', conversionRate: 155.50 },
  { code: 'TTD', symbol: 'TT$', name: 'Trinidad & Tobago Dollar', conversionRate: 6.78 },
  { code: 'BSD', symbol: 'B$', name: 'Bahamian Dollar', conversionRate: 1 },
  { code: 'BBD', symbol: 'Bds$', name: 'Barbadian Dollar', conversionRate: 2 },
  { code: 'DOP', symbol: 'RD$', name: 'Dominican Peso', conversionRate: 59.50 },
  { code: 'HTG', symbol: 'G', name: 'Haitian Gourde', conversionRate: 131.50 },
  { code: 'CUP', symbol: '₱', name: 'Cuban Peso', conversionRate: 24.00 },
  { code: 'GYD', symbol: 'G$', name: 'Guyanese Dollar', conversionRate: 209.00 },
  { code: 'SRD', symbol: 'Sr$', name: 'Surinamese Dollar', conversionRate: 35.25 },
  { code: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina', conversionRate: 3.95 },
  { code: 'SBD', symbol: 'SI$', name: 'Solomon Islands Dollar', conversionRate: 8.45 },
  { code: 'VUV', symbol: 'VT', name: 'Vanuatu Vatu', conversionRate: 118.50 },
  { code: 'WST', symbol: 'WS$', name: 'Samoan Tālā', conversionRate: 2.72 },
  { code: 'TOP', symbol: 'T$', name: 'Tongan Paʻanga', conversionRate: 2.35 },
  { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee', conversionRate: 299.50 },
  { code: 'NPR', symbol: 'Rs', name: 'Nepalese Rupee', conversionRate: 133.00 },
  { code: 'MMK', symbol: 'K', name: 'Myanmar Kyat', conversionRate: 2100.00 },
  { code: 'KHR', symbol: '៛', name: 'Cambodian Riel', conversionRate: 4065.00 },
  { code: 'LAK', symbol: '₭', name: 'Lao Kip', conversionRate: 21850.00 },
];

export const ALL_LANGUAGES: GlobalLanguage[] = [
  { code: 'en-US', name: 'English (US)', nativeName: 'English (US)', rtl: false, region: 'North America' },
  { code: 'en-GB', name: 'English (UK)', nativeName: 'English (UK)', rtl: false, region: 'Europe' },
  { code: 'en-AU', name: 'English (Australia)', nativeName: 'English (Australia)', rtl: false, region: 'Oceania' },
  { code: 'en-CA', name: 'English (Canada)', nativeName: 'English (Canada)', rtl: false, region: 'North America' },
  { code: 'en-IN', name: 'English (India)', nativeName: 'English (India)', rtl: false, region: 'Asia' },
  { code: 'hi-IN', name: 'Hindi', nativeName: 'हिन्दी', rtl: false, region: 'Asia' },
  { code: 'bn-IN', name: 'Bengali', nativeName: 'বাংলা', rtl: false, region: 'Asia' },
  { code: 'te-IN', name: 'Telugu', nativeName: 'తెలుగు', rtl: false, region: 'Asia' },
  { code: 'mr-IN', name: 'Marathi', nativeName: 'मराठी', rtl: false, region: 'Asia' },
  { code: 'ta-IN', name: 'Tamil', nativeName: 'தமிழ்', rtl: false, region: 'Asia' },
  { code: 'gu-IN', name: 'Gujarati', nativeName: 'ગુજરાતી', rtl: false, region: 'Asia' },
  { code: 'kn-IN', name: 'Kannada', nativeName: 'ಕನ್ನಡ', rtl: false, region: 'Asia' },
  { code: 'ml-IN', name: 'Malayalam', nativeName: 'മലയാളം', rtl: false, region: 'Asia' },
  { code: 'pa-IN', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', rtl: false, region: 'Asia' },
  { code: 'ur-PK', name: 'Urdu', nativeName: 'اردو', rtl: true, region: 'Asia' },
  { code: 'es-ES', name: 'Spanish (Spain)', nativeName: 'Español (España)', rtl: false, region: 'Europe' },
  { code: 'es-MX', name: 'Spanish (Mexico)', nativeName: 'Español (México)', rtl: false, region: 'North America' },
  { code: 'es-AR', name: 'Spanish (Argentina)', nativeName: 'Español (Argentina)', rtl: false, region: 'South America' },
  { code: 'fr-FR', name: 'French', nativeName: 'Français', rtl: false, region: 'Europe' },
  { code: 'fr-CA', name: 'French (Canada)', nativeName: 'Français (Canada)', rtl: false, region: 'North America' },
  { code: 'de-DE', name: 'German', nativeName: 'Deutsch', rtl: false, region: 'Europe' },
  { code: 'it-IT', name: 'Italian', nativeName: 'Italiano', rtl: false, region: 'Europe' },
  { code: 'pt-BR', name: 'Portuguese (Brazil)', nativeName: 'Português (Brasil)', rtl: false, region: 'South America' },
  { code: 'pt-PT', name: 'Portuguese (Portugal)', nativeName: 'Português (Portugal)', rtl: false, region: 'Europe' },
  { code: 'ru-RU', name: 'Russian', nativeName: 'Русский', rtl: false, region: 'Europe' },
  { code: 'zh-CN', name: 'Chinese (Simplified)', nativeName: '中文 (简体)', rtl: false, region: 'Asia' },
  { code: 'zh-TW', name: 'Chinese (Traditional)', nativeName: '中文 (繁體)', rtl: false, region: 'Asia' },
  { code: 'ja-JP', name: 'Japanese', nativeName: '日本語', rtl: false, region: 'Asia' },
  { code: 'ko-KR', name: 'Korean', nativeName: '한국어', rtl: false, region: 'Asia' },
  { code: 'ar-SA', name: 'Arabic', nativeName: 'العربية', rtl: true, region: 'Middle East' },
  { code: 'ar-EG', name: 'Arabic (Egypt)', nativeName: 'العربية (مصر)', rtl: true, region: 'Africa' },
  { code: 'ar-AE', name: 'Arabic (UAE)', nativeName: 'العربية (الإمارات)', rtl: true, region: 'Middle East' },
  { code: 'he-IL', name: 'Hebrew', nativeName: 'עברית', rtl: true, region: 'Middle East' },
  { code: 'nl-NL', name: 'Dutch', nativeName: 'Nederlands', rtl: false, region: 'Europe' },
  { code: 'pl-PL', name: 'Polish', nativeName: 'Polski', rtl: false, region: 'Europe' },
  { code: 'tr-TR', name: 'Turkish', nativeName: 'Türkçe', rtl: false, region: 'Europe' },
  { code: 'vi-VN', name: 'Vietnamese', nativeName: 'Tiếng Việt', rtl: false, region: 'Asia' },
  { code: 'id-ID', name: 'Indonesian', nativeName: 'Bahasa Indonesia', rtl: false, region: 'Asia' },
  { code: 'th-TH', name: 'Thai', nativeName: 'ไทย', rtl: false, region: 'Asia' },
  { code: 'ms-MY', name: 'Malay', nativeName: 'Bahasa Melayu', rtl: false, region: 'Asia' },
  { code: 'fil-PH', name: 'Filipino', nativeName: 'Filipino', rtl: false, region: 'Asia' },
  { code: 'sv-SE', name: 'Swedish', nativeName: 'Svenska', rtl: false, region: 'Europe' },
  { code: 'no-NO', name: 'Norwegian', nativeName: 'Norsk', rtl: false, region: 'Europe' },
  { code: 'da-DK', name: 'Danish', nativeName: 'Dansk', rtl: false, region: 'Europe' },
  { code: 'fi-FI', name: 'Finnish', nativeName: 'Suomi', rtl: false, region: 'Europe' },
  { code: 'cs-CZ', name: 'Czech', nativeName: 'Čeština', rtl: false, region: 'Europe' },
  { code: 'el-GR', name: 'Greek', nativeName: 'Ελληνικά', rtl: false, region: 'Europe' },
  { code: 'ro-RO', name: 'Romanian', nativeName: 'Română', rtl: false, region: 'Europe' },
  { code: 'hu-HU', name: 'Hungarian', nativeName: 'Magyar', rtl: false, region: 'Europe' },
  { code: 'bg-BG', name: 'Bulgarian', nativeName: 'Български', rtl: false, region: 'Europe' },
  { code: 'hr-HR', name: 'Croatian', nativeName: 'Hrvatski', rtl: false, region: 'Europe' },
  { code: 'sk-SK', name: 'Slovak', nativeName: 'Slovenčina', rtl: false, region: 'Europe' },
  { code: 'sl-SI', name: 'Slovenian', nativeName: 'Slovenščina', rtl: false, region: 'Europe' },
  { code: 'lt-LT', name: 'Lithuanian', nativeName: 'Lietuvių', rtl: false, region: 'Europe' },
  { code: 'lv-LV', name: 'Latvian', nativeName: 'Latviešu', rtl: false, region: 'Europe' },
  { code: 'et-EE', name: 'Estonian', nativeName: 'Eesti', rtl: false, region: 'Europe' },
  { code: 'uk-UA', name: 'Ukrainian', nativeName: 'Українська', rtl: false, region: 'Europe' },
  { code: 'sr-RS', name: 'Serbian', nativeName: 'Српски', rtl: false, region: 'Europe' },
  { code: 'mk-MK', name: 'Macedonian', nativeName: 'Македонски', rtl: false, region: 'Europe' },
  { code: 'sq-AL', name: 'Albanian', nativeName: 'Shqip', rtl: false, region: 'Europe' },
  { code: 'is-IS', name: 'Icelandic', nativeName: 'Íslenska', rtl: false, region: 'Europe' },
  { code: 'mt-MT', name: 'Maltese', nativeName: 'Malti', rtl: false, region: 'Europe' },
  { code: 'fa-IR', name: 'Persian (Farsi)', nativeName: 'فارسی', rtl: true, region: 'Middle East' },
  { code: 'sw-KE', name: 'Swahili', nativeName: 'Kiswahili', rtl: false, region: 'Africa' },
  { code: 'am-ET', name: 'Amharic', nativeName: 'አማርኛ', rtl: false, region: 'Africa' },
  { code: 'zu-ZA', name: 'Zulu', nativeName: 'isiZulu', rtl: false, region: 'Africa' },
  { code: 'af-ZA', name: 'Afrikaans', nativeName: 'Afrikaans', rtl: false, region: 'Africa' },
  { code: 'ha-NG', name: 'Hausa', nativeName: 'Hausa', rtl: false, region: 'Africa' },
  { code: 'yo-NG', name: 'Yoruba', nativeName: 'Yorùbá', rtl: false, region: 'Africa' },
  { code: 'ig-NG', name: 'Igbo', nativeName: 'Igbo', rtl: false, region: 'Africa' },
  { code: 'my-MM', name: 'Burmese', nativeName: 'မြန်မာ', rtl: false, region: 'Asia' },
  { code: 'km-KH', name: 'Khmer', nativeName: 'ខ្មែរ', rtl: false, region: 'Asia' },
  { code: 'lo-LA', name: 'Lao', nativeName: 'ລາວ', rtl: false, region: 'Asia' },
  { code: 'ne-NP', name: 'Nepali', nativeName: 'नेपाली', rtl: false, region: 'Asia' },
  { code: 'si-LK', name: 'Sinhala', nativeName: 'සිංහල', rtl: false, region: 'Asia' },
  { code: 'ps-AF', name: 'Pashto', nativeName: 'پښتو', rtl: true, region: 'Asia' },
  { code: 'ku-IQ', name: 'Kurdish', nativeName: 'کوردی', rtl: true, region: 'Middle East' },
  { code: 'ka-GE', name: 'Georgian', nativeName: 'ქართული', rtl: false, region: 'Asia' },
  { code: 'hy-AM', name: 'Armenian', nativeName: 'Հայերեն', rtl: false, region: 'Asia' },
  { code: 'az-AZ', name: 'Azerbaijani', nativeName: 'Azərbaycan', rtl: false, region: 'Asia' },
  { code: 'kk-KZ', name: 'Kazakh', nativeName: 'Қазақ', rtl: false, region: 'Asia' },
  { code: 'uz-UZ', name: 'Uzbek', nativeName: 'Oʻzbek', rtl: false, region: 'Asia' },
  { code: 'mn-MN', name: 'Mongolian', nativeName: 'Монгол', rtl: false, region: 'Asia' },
  { code: 'bo-CN', name: 'Tibetan', nativeName: 'བོད་ཡིག', rtl: false, region: 'Asia' },
  { code: 'ug-CN', name: 'Uyghur', nativeName: 'ئۇيغۇر', rtl: true, region: 'Asia' },
  { code: 'yi', name: 'Yiddish', nativeName: 'ייִדיש', rtl: true, region: 'Europe' },
  { code: 'la', name: 'Latin', nativeName: 'Latina', rtl: false, region: 'Europe' },
  { code: 'cy-GB', name: 'Welsh', nativeName: 'Cymraeg', rtl: false, region: 'Europe' },
  { code: 'ga-IE', name: 'Irish', nativeName: 'Gaeilge', rtl: false, region: 'Europe' },
  { code: 'gd-GB', name: 'Scottish Gaelic', nativeName: 'Gàidhlig', rtl: false, region: 'Europe' },
  { code: 'eu-ES', name: 'Basque', nativeName: 'Euskara', rtl: false, region: 'Europe' },
  { code: 'ca-ES', name: 'Catalan', nativeName: 'Català', rtl: false, region: 'Europe' },
  { code: 'gl-ES', name: 'Galician', nativeName: 'Galego', rtl: false, region: 'Europe' },
  { code: 'eo', name: 'Esperanto', nativeName: 'Esperanto', rtl: false, region: 'International' },
  { code: 'jv-ID', name: 'Javanese', nativeName: 'Basa Jawa', rtl: false, region: 'Asia' },
  { code: 'su-ID', name: 'Sundanese', nativeName: 'Basa Sunda', rtl: false, region: 'Asia' },
  { code: 'ceb-PH', name: 'Cebuano', nativeName: 'Binisaya', rtl: false, region: 'Asia' },
  { code: 'hmn', name: 'Hmong', nativeName: 'Hmoob', rtl: false, region: 'Asia' },
  { code: 'mi-NZ', name: 'Maori', nativeName: 'Te Reo Māori', rtl: false, region: 'Oceania' },
  { code: 'sm-WS', name: 'Samoan', nativeName: 'Gagana Samoa', rtl: false, region: 'Oceania' },
  { code: 'to-TO', name: 'Tongan', nativeName: 'Lea Faka-Tonga', rtl: false, region: 'Oceania' },
  { code: 'haw', name: 'Hawaiian', nativeName: 'ʻŌlelo Hawaiʻi', rtl: false, region: 'Oceania' },
  { code: 'mg-MG', name: 'Malagasy', nativeName: 'Malagasy', rtl: false, region: 'Africa' },
  { code: 'sn-ZW', name: 'Shona', nativeName: 'chiShona', rtl: false, region: 'Africa' },
  { code: 'ny-MW', name: 'Chichewa', nativeName: 'Chichewa', rtl: false, region: 'Africa' },
  { code: 'so-SO', name: 'Somali', nativeName: 'Soomaali', rtl: false, region: 'Africa' },
  { code: 'rw-RW', name: 'Kinyarwanda', nativeName: 'Ikinyarwanda', rtl: false, region: 'Africa' },
  { code: 'lg-UG', name: 'Luganda', nativeName: 'Luganda', rtl: false, region: 'Africa' },
];

export function getCurrencyForCountry(countryCode: string): Currency {
  const country = ALL_COUNTRIES.find(c => c.code === countryCode);
  if (!country) return ALL_CURRENCIES[0];
  return ALL_CURRENCIES.find(cur => cur.code === country.currency) || ALL_CURRENCIES[0];
}

export function convertPrice(priceUSD: number, targetCurrency: string): number {
  const currency = ALL_CURRENCIES.find(c => c.code === targetCurrency);
  if (!currency) return priceUSD;
  return Math.round(priceUSD * currency.conversionRate * 100) / 100;
}

export function formatPrice(price: number, currencyCode: string): string {
  const currency = ALL_CURRENCIES.find(c => c.code === currencyCode);
  if (!currency) return `$${price}`;
  return `${currency.symbol}${price.toLocaleString()}`;
}

export function getLanguagesByRegion(region: string): GlobalLanguage[] {
  return ALL_LANGUAGES.filter(lang => lang.region === region);
}

export function isRTLLanguage(languageCode: string): boolean {
  const lang = ALL_LANGUAGES.find(l => l.code === languageCode);
  return lang?.rtl || false;
}

export const RTL_LANGUAGES = ALL_LANGUAGES.filter(lang => lang.rtl).map(lang => lang.code);

export const CURRENCY_REGIONS = {
  'North America': ['USD', 'CAD', 'MXN'],
  'South America': ['BRL', 'ARS', 'CLP', 'COP', 'PEN'],
  'Europe': ['EUR', 'GBP', 'CHF', 'SEK', 'NOK', 'DKK', 'PLN', 'CZK', 'HUF', 'RUB', 'TRY'],
  'Asia': ['INR', 'JPY', 'CNY', 'KRW', 'SGD', 'HKD', 'THB', 'IDR', 'MYR', 'PHP', 'VND', 'PKR', 'BDT'],
  'Middle East': ['AED', 'SAR', 'ILS'],
  'Africa': ['ZAR', 'EGP', 'NGN'],
  'Oceania': ['AUD', 'NZD'],
};
